#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Nov 08 11:23:41 BRT 2022
https\://repo.maven.apache.org/maven2/.lastUpdated=1667917421481
https\://repo.maven.apache.org/maven2/.error=
