#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Nov 08 11:25:30 BRT 2022
https\://repo.maven.apache.org/maven2/.lastUpdated=1667917530860
https\://repo.maven.apache.org/maven2/.error=
